version: '3.8'

services:
  # ArUco Processor Node
  aruco_processor:
    image: weed-detection-node:latest
    container_name: aruco_processor_test
    command: ros2 run weed_detection_node aruco_processor
    networks:
      - ros_network
    environment:
      - ROS_DOMAIN_ID=0

  # Image Publisher (for testing)
  image_publisher:
    image: weed-detection-node:latest
    container_name: image_publisher_test
    command: bash -c "sleep 3 && ros2 run weed_detection_node image_publisher /root/ros2_ws/src/weed_detection_node/test_scene_with_aruco.jpg 0.5"
    networks:
      - ros_network
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - aruco_processor

networks:
  ros_network:
    driver: bridge

